name: Build libgstspotify.so

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - alpine-version: "3.18"
            platform: linux/amd64
            platform-name: linux-amd64
            gst-plugins-rs-tag: gstreamer-1.22.12
          - alpine-version: "3.18"
            platform: linux/arm64
            platform-name: linux-arm64
            gst-plugins-rs-tag: gstreamer-1.22.12
          - alpine-version: "3.19"
            platform: linux/amd64
            platform-name: linux-amd64
            gst-plugins-rs-tag: gstreamer-1.22.12
          - alpine-version: "3.19"
            platform: linux/arm64
            platform-name: linux-arm64
            gst-plugins-rs-tag: gstreamer-1.22.12
          - alpine-version: "3.20"
            platform: linux/amd64
            platform-name: linux-amd64
            gst-plugins-rs-tag: gstreamer-1.24.3
          - alpine-version: "3.20"
            platform: linux/arm64
            platform-name: linux-arm64
            gst-plugins-rs-tag: gstreamer-1.24.3

    env:
      ALPINE_VERSION: ${{ matrix.alpine-version }}
      TARGET_PLATFORM: ${{ matrix.platform }}
      PLATFORM_NAME: ${{ matrix.platform-name }}
      GST_PLUGINS_RS_TAG: ${{ matrix.gst-plugins-rs-tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build libgstspotify.so
        run: |
          docker buildx build --platform ${{ matrix.platform }} --tag libgstspotify-builder \
            --tag libgstspotify-${{ matrix.alpine-version }}-builder \
            --load --target final \
            --build-arg GST_PLUGINS_RS_TAG=${{ env.GST_PLUGINS_RS_TAG }} \
            --build-arg ALPINE_VERSION=${{ env.ALPINE_VERSION }} \
            --progress=plain .

      - name: Save libgstspotify.so and checksums
        run: |
          # Create directory specific to platform, Alpine version, and GStreamer version
          output_dir="./output/${{ matrix.platform-name }}/alpine-${{ matrix.alpine-version }}/gst-${{ env.GST_PLUGINS_RS_TAG }}"
          mkdir -p $output_dir

          # Create a Docker container from the built image
          docker create --name libgstspotify-container libgstspotify-builder

          # Copy the so file from the container to the host
          docker cp libgstspotify-container:/usr/lib/gstreamer-1.0/libgstspotify.so $output_dir/libgstspotify.so

          # Generate SHA256 checksum for the so file
          sha256sum $output_dir/libgstspotify.so > $output_dir/libgstspotify.so.sha256

          # Create a tar archive of the so file
          tar czf $output_dir/libgstspotify.tar.gz -C $output_dir libgstspotify.so

          # Generate SHA256 checksum for the tar archive
          sha256sum $output_dir/libgstspotify.tar.gz > $output_dir/libgstspotify.tar.gz.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpine-${{ env.ALPINE_VERSION }}-${{ matrix.platform-name }}_${{ env.GST_PLUGINS_RS_TAG }}_libgstspotify
          path: ./output/${{ matrix.platform-name }}/alpine-${{ env.ALPINE_VERSION }}
