name: Build libgstspotify.so

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      dockerfile_hash: ${{ steps.calculate_hash.outputs.hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate Dockerfile hash
        id: calculate_hash
        run: |
          echo "hash=$(sha256sum Dockerfile | awk '{print $1}')" >> $GITHUB_ENV

  build_amd64:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_version: ['3.18', '3.19', '3.20']
    env:
      GST_PLUGINS_RS_TAG: 0.14.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v4
        with:
          path: ./output/linux/amd64/alpine${{ matrix.alpine_version }}
          key: ${{ runner.os }}-amd64-alpine${{ matrix.alpine_version }}-libgstspotify-${{ needs.prepare.outputs.dockerfile_hash }}-${{ env.GST_PLUGINS_RS_TAG }}
          restore-keys: |
            ${{ runner.os }}-amd64-alpine${{ matrix.alpine_version }}-libgstspotify-${{ needs.prepare.outputs.dockerfile_hash }}-

      - name: Set up Docker Buildx
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build libgstspotify.so
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          docker buildx build --platform linux/amd64 --tag libgstspotify-builder-alpine${{ matrix.alpine_version }} --load --target final --build-arg GST_PLUGINS_RS_TAG=${{ env.GST_PLUGINS_RS_TAG }} --build-arg ALPINE_VERSION=${{ matrix.alpine_version }} --progress=plain .

  build_arm64:
    needs: prepare
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    strategy:
      matrix:
        alpine_version: ['3.18', '3.19', '3.20']
    env:
      GST_PLUGINS_RS_TAG: 0.14.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: ./output/linux/arm64/alpine${{ matrix.alpine_version }}
          key: ${{ runner.os }}-arm64-alpine${{ matrix.alpine_version }}-libgstspotify-${{ needs.prepare.outputs.dockerfile_hash }}-${{ env.GST_PLUGINS_RS_TAG }}
          restore-keys: |
            ${{ runner.os }}-arm64-alpine${{ matrix.alpine_version }}-libgstspotify-${{ needs.prepare.outputs.dockerfile_hash }}-

      - name: Set up Docker Buildx
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build libgstspotify.so
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          docker buildx build --platform linux/arm64 --tag libgstspotify-builder-alpine${{ matrix.alpine_version }} --load --target final --build-arg GST_PLUGINS_RS_TAG=${{ env.GST_PLUGINS_RS_TAG }} --build-arg ALPINE_VERSION=${{ matrix.alpine_version }} --progress=plain .
